### ISSUE TITLE
Edit the admin form

### ISSUE THREAD

**Issue by sowmi20189** [rubyforgood/inkind-admin#198]
#Summary

An admin should be able to edit the information of any admin.

## Things to Consider
Currently, first name, last name, email and phone number can be edited.

# Criteria for Completion
 - [ ] Admin should be able to edit the assign student field 
 - [ ] Be able to remove existing assigned student
 - [ ] Be able to edit and add a new student
 - [ ] Be able to edit all the fields (first name, last name, phone number, email)
 - [ ] Have the buttons deactivate and save according to the UI guidelines 

<img width="871" alt="Edit Admin form" src="https://user-images.githubusercontent.com/96266018/153498338-af10a405-0bf3-43f1-a53b-80715853bae2.png">

**Comment by garettarrowood** [comment]
New/Edit forms in this program share the same template. Because of this, #197 is pretty much the same story. There are definitely some differences between processing a new admin versus editing one. But in regards to updating UI styles and getting the student multiselect functioning, these have more in common than they differ. Closing this issue in preference of #197
